language: python
install:
  - pip install coveralls
script:
  nosetests --with-coverage --with-isolation -v tex2Wiki DLMF_preprocessing maple2latex main_page eCF KLSadd_insertion
after_success:
  coveralls
